package com.ppio.third.mgtv.mapper;

import com.ppio.third.mgtv.entity.TMgtvAccesslogMachine;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TMgtvAccesslogMachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_machine
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_machine
     *
     * @mbg.generated
     */
    int insert(TMgtvAccesslogMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_machine
     *
     * @mbg.generated
     */
    int insertSelective(TMgtvAccesslogMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_machine
     *
     * @mbg.generated
     */
    TMgtvAccesslogMachine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMgtvAccesslogMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMgtvAccesslogMachine record);

    TMgtvAccesslogMachine selectByMachineIP( @Param("machineId") String machineId,@Param("ip") String ip);

    List<TMgtvAccesslogMachine> getOnlineMachines();


}