package com.ppio.third.mgtv.mapper;

import com.ppio.third.mgtv.entity.TMgtvAccesslogItems;
import org.apache.ibatis.annotations.Param;

public interface TMgtvAccesslogItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_items
     *
     * @mbg.generated
     */
    int insert(TMgtvAccesslogItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_items
     *
     * @mbg.generated
     */
    int insertSelective(TMgtvAccesslogItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_items
     *
     * @mbg.generated
     */
    TMgtvAccesslogItems selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMgtvAccesslogItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgtv_accesslog_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMgtvAccesslogItems record);

    TMgtvAccesslogItems selectByMachineidAndFilename(@Param("machineId") String machineId, @Param("filename") String filename);
}