package com.ppio.third.mgtv.entity;

import lombok.ToString;

import java.util.Date;

@ToString
public class TMgtvAccesslogItems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.id
     *
     * @mbg.generated
     */
    private Long id;

    private String ip ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.machine_id
     *
     * @mbg.generated
     */
    private String machineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.dt
     *
     * @mbg.generated
     */
    private String dt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mgtv_accesslog_items.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.id
     *
     * @return the value of t_mgtv_accesslog_items.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.id
     *
     * @param id the value for t_mgtv_accesslog_items.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.machine_id
     *
     * @return the value of t_mgtv_accesslog_items.machine_id
     *
     * @mbg.generated
     */
    public String getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.machine_id
     *
     * @param machineId the value for t_mgtv_accesslog_items.machine_id
     *
     * @mbg.generated
     */
    public void setMachineId(String machineId) {
        this.machineId = machineId == null ? null : machineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.url
     *
     * @return the value of t_mgtv_accesslog_items.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.url
     *
     * @param url the value for t_mgtv_accesslog_items.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.file_name
     *
     * @return the value of t_mgtv_accesslog_items.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.file_name
     *
     * @param fileName the value for t_mgtv_accesslog_items.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.dt
     *
     * @return the value of t_mgtv_accesslog_items.dt
     *
     * @mbg.generated
     */
    public String getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.dt
     *
     * @param dt the value for t_mgtv_accesslog_items.dt
     *
     * @mbg.generated
     */
    public void setDt(String dt) {
        this.dt = dt == null ? null : dt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.status
     *
     * @return the value of t_mgtv_accesslog_items.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.status
     *
     * @param status the value for t_mgtv_accesslog_items.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.create_time
     *
     * @return the value of t_mgtv_accesslog_items.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.create_time
     *
     * @param createTime the value for t_mgtv_accesslog_items.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mgtv_accesslog_items.update_time
     *
     * @return the value of t_mgtv_accesslog_items.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mgtv_accesslog_items.update_time
     *
     * @param updateTime the value for t_mgtv_accesslog_items.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}