package com.ppio.third.mgtv.entity;

import java.util.Date;

public class TThirdMgtvQuality {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.id
     *
     * @mbg.generated
     */
//    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.isp
     *
     * @mbg.generated
     */
    private String isp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.resource
     *
     * @mbg.generated
     */
    private String resource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.kd_ratio
     *
     * @mbg.generated
     */
    private Double kdRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.error_ratio
     *
     * @mbg.generated
     */
    private Double errorRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_third_mgtv_quality.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.id
     *
     * @return the value of t_third_mgtv_quality.id
     *
     * @mbg.generated
     */
//    public Long getId() {
//        return id;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.id
     *
     * @param id the value for t_third_mgtv_quality.id
     *
     * @mbg.generated
     */
//    public void setId(Long id) {
//        this.id = id;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.time
     *
     * @return the value of t_third_mgtv_quality.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.time
     *
     * @param time the value for t_third_mgtv_quality.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.region
     *
     * @return the value of t_third_mgtv_quality.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.region
     *
     * @param region the value for t_third_mgtv_quality.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.isp
     *
     * @return the value of t_third_mgtv_quality.isp
     *
     * @mbg.generated
     */
    public String getIsp() {
        return isp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.isp
     *
     * @param isp the value for t_third_mgtv_quality.isp
     *
     * @mbg.generated
     */
    public void setIsp(String isp) {
        this.isp = isp == null ? null : isp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.resource
     *
     * @return the value of t_third_mgtv_quality.resource
     *
     * @mbg.generated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.resource
     *
     * @param resource the value for t_third_mgtv_quality.resource
     *
     * @mbg.generated
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.kd_ratio
     *
     * @return the value of t_third_mgtv_quality.kd_ratio
     *
     * @mbg.generated
     */
    public Double getKdRatio() {
        return kdRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.kd_ratio
     *
     * @param kdRatio the value for t_third_mgtv_quality.kd_ratio
     *
     * @mbg.generated
     */
    public void setKdRatio(Double kdRatio) {
        this.kdRatio = kdRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.error_ratio
     *
     * @return the value of t_third_mgtv_quality.error_ratio
     *
     * @mbg.generated
     */
    public Double getErrorRatio() {
        return errorRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.error_ratio
     *
     * @param errorRatio the value for t_third_mgtv_quality.error_ratio
     *
     * @mbg.generated
     */
    public void setErrorRatio(Double errorRatio) {
        this.errorRatio = errorRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.create_time
     *
     * @return the value of t_third_mgtv_quality.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.create_time
     *
     * @param createTime the value for t_third_mgtv_quality.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_third_mgtv_quality.update_time
     *
     * @return the value of t_third_mgtv_quality.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_third_mgtv_quality.update_time
     *
     * @param updateTime the value for t_third_mgtv_quality.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}